//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IO2017Entities : DbContext
    {
        public IO2017Entities()
            : base("name=IO2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bed_types> bed_types { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<room_statuses> room_statuses { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
