//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rooms()
        {
            this.reservations = new HashSet<reservations>();
        }
    
        public int room_id { get; set; }
        public int number { get; set; }
        public decimal price { get; set; }
        public bool smoking { get; set; }
        public bool pets { get; set; }
        public int room_status { get; set; }
        public int bed_type { get; set; }
    
        public virtual bed_types bed_types { get; set; }
        public virtual room_statuses room_statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservations> reservations { get; set; }
    }
}
